name: Test 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests on CentOS-Stream8
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args: "-p CentOS-stream8"

      - name: Run tests on rocky9
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args: "-p rocky9"

      - name: Run tests on ubuntu2204
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args: "-p ubuntu2204"
